app:
  #系统组件网卡默认驱动，可选值为virtio e1000 rtl8139,变更该值需要删除原系统组件重建，切为最新版本的系统组件模版文件
  systemComponentNetworkDriver: virtio
  systemComponentCpu: 1
  systemComponentMemory: 1048576
  systemComponentCpuSpeed: 0
  destroyDelayMinute: 3
  # 是否启用大页内存，如果启用，在宿主机为ubuntu下请设置vm.nr_hugepages，否则虚拟机无法启动
  enableMemoryHugePages: false
  manager-uri: http://192.168.2.193:8080/
  over-cpu: 4.0
  over-memory: 2.0
  #系统组 pip3加速源，国内用户可配置，海外无需配置
  pip-source: https://pypi.tuna.tsinghua.edu.cn/simple
#  系统组件yum加速源(Oracle linux 9.4.0)，国内用户可配置，海外无需配置，如果启用该配置，需保证加速源正常访问
#  yum-source: |
#    [ol9_baseos_latest]
#    name=Oracle Linux 9 BaseOS Latest ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/baseos/latest/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=1
#
#    [ol9_appstream]
#    name=Oracle Linux 9 Application Stream Packages ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/appstream/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=1
#
#    [ol9_u0_baseos_base]
#    name=Oracle Linux 9 BaseOS GA ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/0/baseos/base/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_u1_baseos_base]
#    name=Oracle Linux 9.1 BaseOS ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/1/baseos/base/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_u2_baseos_base]
#    name=Oracle Linux 9.2 BaseOS ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/2/baseos/base/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_u3_baseos_base]
#    name=Oracle Linux 9.3 BaseOS ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/3/baseos/base/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_u4_baseos_base]
#    name=Oracle Linux 9.4 BaseOS ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/4/baseos/base/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_u5_baseos_base]
#    name=Oracle Linux 9.5 BaseOS ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/5/baseos/base/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_addons]
#    name=Oracle Linux 9 Addons ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/addons/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_codeready_builder]
#    name=Oracle Linux 9 CodeReady Builder ($basearch) - (Unsupported)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/codeready/builder/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_distro_builder]
#    name=Oracle Linux 9 Distro Builder ($basearch) - (Unsupported)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/distro/builder/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
#
#    [ol9_MODRHCK]
#    name=Latest RHCK with fixes from Oracle for Oracle Linux $releasever ($basearch)
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/MODRHCK/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    priority=20
#    enabled=0
#
#    [ol9_u3_security_validation]
#    name=Oracle Linux $releasever Update 3 ($basearch) Security Validations
#    baseurl=https://yum$ociregion.$ocidomain/repo/OracleLinux/OL9/3/security/validation/$basearch/
#    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
#    gpgcheck=1
#    enabled=0
  work:
    thread:
      size: 1

server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      stat-view-servlet.enabled: false
      initial-size: 8
      max-idle: 8
      max-active: 16
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 32
      max-pool-prepared-statement-per-connection-size: 32
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.90:3306/cj_kvm_cloud?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    username: root
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100GB
      max-request-size: 100GB
  redis:
    redisson:
      config: |
        singleServerConfig:
         idleConnectionTimeout: 10000
         connectTimeout: 10000
         timeout: 3000
         retryAttempts: 3
         retryInterval: 1500
         address: "redis://192.168.1.90:6379"
         password: 
         database: 0
         subscriptionsPerConnection: 5
         subscriptionConnectionMinimumIdleSize: 1
         subscriptionConnectionPoolSize: 50
         connectionMinimumIdleSize: 32
         connectionPoolSize: 64
         database: 2
         dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
