app:
  #系统组件网卡默认驱动，可选值为virtio e1000 rtl8139,变更该值需要删除原系统组件重建，切为最新版本的系统组件模版文件
  systemComponentNetworkDriver: virtio
  systemComponentCpu: 1
  systemComponentMemory: 524288
  systemComponentCpuSpeed: 500
  #通过模版创建是否启用backing file,为false时通过clone磁盘实现,如果磁盘空间充足，可修改为false，该值为false时通过模版创建系统耗时会变长
  enableVolumeBack: false
  manager-uri: http://192.168.2.107:8080/
  over-cpu: 4.0
  over-memory: 2.0
  route:
      #支持dnsmasq 与dhcp两种配置，变更该值必须重建所有网络的System Route,版本升级尤其注意,dhcp模式不支持metaservice
      type: dnsmasq
  work:
    thread:
      size: 16
  boss:
    thread:
      size: 4

oauth2:
  auth-uri: https://192.168.1.2:8083/oauth2/authorize
  client-id: NLMAv72e
  client-secret: fd74a2cb8b62d4011ff5945b0204d07f68366848
  enable: false
  id-path:
    - userId
  redirect-uri: http://192.168.2.107:8081/#/Login
  title: Oauth2 Login
  token-uri: https://192.168.1.2:8083/oauth2/token
  user-uri: https://192.168.1.2:8083/oauth2/user/info
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.90:3306/cj_kvm_cloud?characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true
    username: root
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100GB
      max-request-size: 100GB
  redis:
    redisson:
      config: |
        singleServerConfig:
         idleConnectionTimeout: 10000
         connectTimeout: 10000
         timeout: 3000
         retryAttempts: 3
         retryInterval: 1500
         address: "redis://192.168.1.90:6379"
         password: 
         database: 0
         subscriptionsPerConnection: 5
         subscriptionConnectionMinimumIdleSize: 1
         subscriptionConnectionPoolSize: 50
         connectionMinimumIdleSize: 32
         connectionPoolSize: 64
         database: 2
         dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"