app:
  #启动后请修改系统配置项default.cluster.manager.uri
  manager-uri: http://192.168.2.193:8080/
  work:
    thread:
      size: 8
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      stat-view-servlet.enabled: false
      initial-size: 8
      max-idle: 8
      max-active: 16
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 32
      max-pool-prepared-statement-per-connection-size: 32
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.90:3306/cj_kvm_cloud?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    username: root
  redis:
    redisson:
      config: |
        singleServerConfig:
         idleConnectionTimeout: 10000
         connectTimeout: 10000
         timeout: 3000
         retryAttempts: 3
         retryInterval: 1500
         address: "redis://192.168.1.90:6379"
         password: 
         database: 0
         subscriptionsPerConnection: 5
         subscriptionConnectionMinimumIdleSize: 1
         subscriptionConnectionPoolSize: 50
         connectionMinimumIdleSize: 32
         connectionPoolSize: 64
         dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
