app:
  #系统组件网卡默认驱动，可选值为virtio e1000 rtl8139,变更该值需要删除原系统组件重建，切为最新版本的系统组件模版文件
  systemComponentNetworkDriver: virtio
  systemComponentCpu: 1
  systemComponentMemory: 524288
  systemComponentCpuSpeed: 0
  manager-uri: http://localhost:8080/
  over-cpu: 4.0
  over-memory: 2.0
  #pip3加速源，国内用户可配置，海外无需配置
  pip-source: https://pypi.tuna.tsinghua.edu.cn/simple
  #yum加速源，国内用户可配置，海外无需配置
  yum-source: |
    [base]
    name=CentOS-$releasever - Base
    baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/os/$basearch/
    gpgcheck=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    
    [updates]
    name=CentOS-$releasever - Updates
    baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/updates/$basearch/
    gpgcheck=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    
    [extras]
    name=CentOS-$releasever - Extras
    baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/extras/$basearch/
    gpgcheck=1
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
    
    [centosplus]
    name=CentOS-$releasever - Plus
    baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos/$releasever/centosplus/$basearch/
    gpgcheck=1
    enabled=0
    gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  work:
    thread:
      size: 16
  boss:
    thread:
      size: 4

oauth2:
  auth-uri: https://192.168.1.2:8083/oauth2/authorize
  client-id: NLMAv72e
  client-secret: fd74a2cb8b62d4011ff5945b0204d07f68366848
  enable: false
  id-path:
    - userId
  redirect-uri: http://192.168.2.107:8081/#/Login
  title: Oauth2 Login
  token-uri: https://192.168.1.2:8083/oauth2/token
  user-uri: https://192.168.1.2:8083/oauth2/user/info
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      stat-view-servlet.enabled: false
      initial-size: 8
      max-idle: 8
      max-active: 16
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 32
      max-pool-prepared-statement-per-connection-size: 32
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.90:3306/cj_kvm_cloud?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    username: root
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100GB
      max-request-size: 100GB
  redis:
    redisson:
      config: |
        singleServerConfig:
         idleConnectionTimeout: 10000
         connectTimeout: 10000
         timeout: 3000
         retryAttempts: 3
         retryInterval: 1500
         address: "redis://192.168.1.90:6379"
         password: 
         database: 0
         subscriptionsPerConnection: 5
         subscriptionConnectionMinimumIdleSize: 1
         subscriptionConnectionPoolSize: 50
         connectionMinimumIdleSize: 32
         connectionPoolSize: 64
         database: 2
         dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"